version: '3'

services:
  flaskapp:
    build: ./flaskapp
    container_name: flaskapp
    networks:
      - backend

  nginx:
    build: ./nginx
    environment:
      - SERVER_NAME=3.223.101.105
    restart: always
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
